# Generated by Django 5.1.3 on 2024-12-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_album_cover_image_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='collection/album_covers/'),
        ),
    ]
